#!/bin/bash
#PBS -P z67
#PBS -q normal
#PBS -l walltime=24:00:00
#PBS -l mem=50GB
#PBS -l ncpus=1
#PBS -l wd

module use /g/data/v10/public/modules/modulefiles

module load agdc-py2-prod
python Palaeovalley_NDVI_linear_regression_raijin.py > Run_NDVI_regression_output













